# Generated by Django 3.1.4 on 2020-12-31 10:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('screenshot', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('link', models.URLField()),
            ],
        ),
    ]
